### ISSUE TITLE
VulkanMemoryAllocation move assignment not returning memory to Page?

### ISSUE THREAD

**Issue by cneumann** [DiligentGraphics/DiligentCore#149]
Hi, this is something I stumbled upon while looking through the code, so it may be purely theoretical:
```cpp
VulkanMemoryAllocation& operator= (VulkanMemoryAllocation&& rhs)noexcept
{
    Page            = rhs.Page;
    UnalignedOffset = rhs.UnalignedOffset;
    Size            = rhs.Size;

    rhs.Page            = nullptr;
    rhs.UnalignedOffset = 0;
    rhs.Size            = 0;

    return *this;
}
```
If `Page != nullptr` the allocation managed by the assignment target is leaked (not returned to the owning Page) - again it is entirely possible this never happens in practice, but it looks like a problem waiting to happen ;)

**Comment by TheMostDiligent** [comment]
Hi!
Thanks for researching this, but this is in fact intentional: when an allocation is destroyed, it [returns itself](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanMemoryManager.cpp#L39) to the owning page. The page then [frees this allocation](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanMemoryManager.cpp#L115), however there still exists `VulkanMemoryAllocation` variable that was created when the function was [entered](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanMemoryManager.cpp#L109).
This variable [is invalidated](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanMemoryManager.cpp#L116) and this is when move-assignment is called. It is crucial here that the destructor is not called because this will result in infinite recursion and releasing the allocation multiple times.
