### ISSUE TITLE
Advice for dealing with DX12 TDRs 

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#288]
Hello, i'm seeking for some advice dealing with DirectX12 device removals more gracefully.

This error occurs an one specific machine with my program, while it runs fine on a few other machines.
```text
D3D12 ERROR: ID3D12Device::RemoveDevice: 
Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: 
The Device took an unreasonable amount of time to execute its commands, or the hardware 
crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been 
triggered. The current Device Context was executing commands when the hang occurred. 
The application may want to respawn and fallback to less aggressive use of the display 
hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
```
I think this is a display driver issue(didn't update the driver to confirm yet because i want to dig more into this). I'm curious though whether there's way to capture this situation and prompt the user gracefully. Some Diligent Engine APIs start failing after the device removal but it's a little hard to recognize what's happening under the hood from the running program...

Could you give some suggestions? Thanks!

**Comment by TheMostDiligent** [comment]
After device removal, all DX functions that return error codes will return `DXGI_ERROR_DEVICE_REMOVED`. However, like I said, many functions have no return values and silently fail. Usually if device gets removed, the program doesn't get to Present, while checking if the device has been removed after every single call is going to introduce extremely high overhead.
I guess it is better to figure out why the device has been removed and fix the problem in the first place rather than trying to handle the aftermath.

**Comment by crlf0710** [comment]
Fair enough, thanks!
