### ISSUE TITLE
Unhandled Exception every time ShaderResourceBinfing->GetVariable(#, #)->Set(TexSRV) is called.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#50]
Hello, every time I call `mSRB->GetVariable(#, "#)->Set(Tex_SRV)` an exception is thrown on every renderer.
I traced all of them to a "RefCntAutoPtr" constructer.
```
RefCntAutoPtr(IObject* pObj, const INTERFACE_ID& IID) noexcept
 :  m_pObject(nullptr)
 {
      if(pObj)
         pObj->QueryInterface( IID, reinterpret_cast<IObject**>(&m_pObject) );  //<<This Line
 }
```

The constructor is called from these location:

On [D3D12](https://github.com/DiligentGraphics/DiligentCore/blob/a7a76b1173a2bd2b768e910b72e5ff3a5b61b93f/Graphics/GraphicsEngineD3D12/src/ShaderResourceLayoutD3D12.cpp#L424).
On [D3D11](https://github.com/DiligentGraphics/DiligentCore/blob/a7a76b1173a2bd2b768e910b72e5ff3a5b61b93f/Graphics/GraphicsEngineD3D11/src/ShaderResourceLayoutD3D11.cpp#L454).
On [Vulkan](https://github.com/DiligentGraphics/DiligentCore/blob/a7a76b1173a2bd2b768e910b72e5ff3a5b61b93f/Graphics/GraphicsEngineVulkan/src/ShaderResourceLayoutVk.cpp#L362).

It is worth noting that I noticed every `ITextureView` I create has the same address in memory...

**Comment by zlixine** [comment]
Also is there a way to control Diligent Engine log output?

**Comment by DiligentGraphics** [comment]
I will need little bit more information to debug this issue as this function [definitely works when used as expected](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial03_Texturing/src/Tutorial03_Texturing.cpp#L249).

Make sure that `mSRB->GetVariable(#, "#)` is not null. Note that only mutable and dynamic variables are accessed through SRB. Static variables are set directly through shaders.

**Comment by zlixine** [comment]
Here are the code snippets: 

[Sample (where SRB set variable is called).](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Samples/Sample1.h)

[Texture SRV Creation.](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Managers/CreateTextureFromRawImage.h)

**Comment by DiligentGraphics** [comment]
OK, so `mSRB->GetVariable(SHADER_TYPE_PIXEL, "NEMat_Diffuse1")` definitely returns `nullptr`, because when you create the PSO, you do not tell the engine that `NEMat_Diffuse1` is a mutable/dynamic variable and should be accessed through SRB. By default, shader variables are static and should be set through shader directly. You need to [explicitly set the variable type](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial03_Texturing/src/Tutorial03_Texturing.cpp#L104).
Please read [this page](http://diligentgraphics.com/2016/03/23/resource-binding-model-in-diligent-engine-2-0/) to learn about shader resource binding in Diligent Engine.

For texture views, `GetDefaultView()` always returns the same pointer to the same default view of a texture. If you need to create other views, use `CreateView()` method.

**Comment by DiligentGraphics** [comment]
Will close this issue for now. Feel free to reopen or create another one if you have any problems.
