### ISSUE TITLE
Shader creation isn't quite flexable.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#51]
Hello, I found great difficulty in implementing Diligent into my Engine due to its heavy abstraction of shader creation. Let me explain to you.
To create a shader we need only one thing (ShaderCreationAttribs) which hides all real data from the user/client.

A typical game engine does the following:
1- Compile shader from source, then translate it into other language if necessary (ex: HLSL to GLSL)
2- Reflect all data necessary.
3- Combine the compiled shader and its reflected data to a structure (aka ShaderBlob)
4- Create GPU shader in the graphical backend.

So the engine have full access to (Compiled shader, shader reflected data and the GPU shader program).
Diligent hides compiled shader and requires the user to query reflection data by IShader->GetVariable() which isn't really practical, a better implementation would be grouping all reflection data into a class.

Plus, Diligent require engines declare the type of a variable at the shader creation that makes things worse.

In my opinion shader creation should be separated to multiple stages/functions that will ease integration into engines.

I want to hear your suggestion, I am ready to modify diligent and do my best.

**Comment by DiligentGraphics** [comment]
I would like to understand what problem you have in the first place. If you need to use compiled byte code, you can absolutely do that. Diligent accepts both SPIRV for Vulkan and DX byte code for D3D11/D3D12. You can use any compiler of your choice and create shaders from compiled blobs.

For reflection, again, I'd like to understand what exactly your problem is. Shader binding is that part that differs dramatically in all 4 supported graphics APIs. There is absolutely no common denominator (shader registers in D3D11 plus root signature in D3D12, locations and bindings in GL plus pipeline layout in Vulkan). Diligent tries to automate shaders resource binding and make it uniform on all platforms and back-ends. It gives you the list of all resources andhl hides details that do not seem to be important.

If what you need is accessible to API-specific reflection data, that can be expired but it will not be in common API.

So, again, without knowing your real issue I can't talk about solutions.

**Comment by zlixine** [comment]
I need to generate ShaderVariableDesc at runtime using reflection data obtained from shader compiling, but since the shader creation abstracts both shader compiling and reflection, I can't do that.

**Comment by zlixine** [comment]
If it is possible, can you separate shader creation into two stages:
Shader compiling (produce compiled shader source and reflection).
Shader reflection (uses compiled shader source and reflection).

**Comment by DiligentGraphics** [comment]
Could you elaborate a bit on why you need reflection before you compile the shader? The assumption was that when you compile the shader, you know which resources every shader uses, so you can set the variable types. Is it not the case in your scenario?

**Comment by DiligentGraphics** [comment]
I think what you are asking for can be implemented, but this would be quite a change, so I am trying to better understand your use case.

**Comment by zlixine** [comment]
Look let's just separate the stages:
Compiling shader (means compiling HLSL to byte code or to GLSL).
Reflection is generated from compiling shader.
Creating shader by using the compiled shader and its reflection.

and yes I need the reflection data to set the variable types, since I want to automate the whole shader creation process.

**Comment by DiligentGraphics** [comment]
It doesn't work this way. I don't make changes to the engine when I'm directed "look just do that". Instead, I make changes when they solve a problem and when they are widely useful. I'm trying really hard to understand what exactly you are struggling with but still have very little idea and can only guess how you use reflection information. Knowing you use case will only help me beter design the API. If you want to set all variables to a specific type, you can use DefaultVariableType member.

If you look at any API, there is no such thing as "compiled shader" at the API level. Compiled shader is simply raw bytes. At the API level the shader represents a program that can be executed on the GPU, created from the raw byte code (with the exception for OpenGL). Diligent does not need another object to represent that. 
Other thing is that in fact, variable types are needed at PSO creation stage, not at shader creation. Moving them to PSO creation will make the API more flexible and should also solve your problem (whatever it is). But I need to think how to bind static resources in this case.

**Comment by DiligentGraphics** [comment]
https://github.com/DiligentGraphics/DiligentCore/issues/8

**Comment by zlixine** [comment]
Sorry, I didn't mean to "direct" you, I will try to explain better.

In almost any graphical APIs, there are 2 stages of shader creation:
1 - Shader Compiling.
2 - Shader Program Creation.

- Shader source: is HLSL in Diligent (I know Diligent allow using others).
- Compiled shader source: is (DXBC for DirectX, GLSL for OpenGL, SPIR-V for Vulkan).

Shader compiling takes shader source and produce (Compiled shader source, shader reflection).
Shader program creation uses the compiled shader source only.

Now diligent encapsulates all these things into one fixed function "CreateShader", and its only argument is ShaderCreationAttribs.

My real issue is automating the whole shader creation process, but to do that I need "Shader Reflection" to generate "ShaderDesc" at runtime, as Diligent requires the engine to set variables types before Shader creation.

Diligent produces Reflection data after shader creation (I need it after compiling, and before creation), and making it worse, Diligent encapsulates reflection data into IShader and it is really limited by variables only and has no data about variable types or macros.

For completeness sake here is some examples:

Creating shader in Diligent: 
```
	ShaderCreationAttribs CreationAttribs;
	
	GetDevice()->CreateShader(CreationAttribs, &pShader);
	// Reflection data is now available, but it has no importance now since we created the shader,but there is a dirty workaround"
	// Create a dummy shader to extract reflection data, copy the data then release the shader.
	// Create the real shader and fill ShaderDesc.ShaderVariableDesc using the reflection data obtained from dummy shader.
	
```
What it should be:
```
	ShaderCompilingAttribs CompilingAttribs;
	CompiledShader compiledShader;
	ShaderReflection compiledShaderReflection;

	GetDevice()->CompileShader(CompilingAttribs, &compiledShader, &compiledShaderReflection);
	// Reflection data is now available, and we can use it to generate ShaderDesc.ShaderVariableDesc using it.
	
	ShaderCreationAttribs CreationAttribs;
	
	// GenerateVariableDesc automates the creation of ShaderVariableDesc using reflection data.
	CreationAttribs.Desc.ShaderVariableDesc = Engine::GenerateVariableDesc(compiledShaderReflection);
	CreationAttribs.Reflection = compiledShaderReflection;
	CreationAttribs.CompiledShader = compiledShader;
	
	GetDevice()->CreateShader(CreationAttribs, &pShader);
```

**Comment by DiligentGraphics** [comment]
OK, I see. So as I mentioned earlier, the problem here isn't really the absence of CompiledShader object in the API, but rather the fact that CreationAttribs requires you to specify variable types. This is indeed not an ideal way due to few other reasons.

To fix the issue I am planning to make the following changes to the API (https://github.com/DiligentGraphics/DiligentCore/issues/8):
* Remove variable types when creating shader object.
* Add reflection function to IShader interface.
  * For every variable, you will be able to query its name, array size and type
* Move variable type specific to PSO creation stage
  * Variable types are key to creating root signature and pipeline layout in Vulkan

With this change you should be able to create shader first, enumerate all resources and then specify variable types when you create the PSO.

This is a big change and will require quite a lot of work. Meanwhile I guess you can use the following workaround:
* Create shader setting `DefaultVariableType` to `SHADER_VARIABLE_TYPE_STATIC` and get the list of all variables from the shader
* Create shader second time using information from the first step

**Comment by DiligentGraphics** [comment]
Also, as I mentioned earlier, compiled shader is really just an array of bytes, nothing more. This object is well represented by blob interface and does not really need anything more sophisticated.
Besides, games do not really compile shaders at run-time. Instead, they compile shaders as part of their build process and ship only bytecode with the application.
Diligent allows compiling shaders at run-time for developer convenience, but for real applications the expected use case is using bytecode only for shader creation.

**Comment by zlixine** [comment]
I know, I am only interested in reflection data before creating the shader.

**Comment by DiligentGraphics** [comment]
OK, I will work on this next as I was planning to improve shader resource layout creation anyway. As I said, this will be quite a change, so it will take some time.

**Comment by DiligentGraphics** [comment]
@zlixine FYI, I finally rolled out this API change. Now shader variable types and static samplers are specified as part of the pipeline state creation process:
https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/PipelineState.h#L225
After you create a shader, you can query the number of resources, and for every resource you can then query its name, type and array size:
https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/Shader.h#L244

I am going to also add API-specific queries later.

**Comment by zlixine** [comment]
@DiligentGraphics , Great thanks!
Sorry for replying so late, but I was busy with real life and had some problems with my pc internet connectivity so I stopped programming for a while.
I will start testing the new changes after getting my engine up and running using diligent again.

**Comment by DiligentGraphics** [comment]
For HLSL shaders, you can also query shader register:
https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineD3DBase/interface/ShaderD3D.h#L42
