### ISSUE TITLE
Reserved resources / tiled resources

### ISSUE THREAD

**Issue by gjaegy** [DiligentGraphics/DiligentCore#77]
Hi,
Our current D3D11-based engine is using tiled resources. From what I've seen, DiligentCore doesn't provide any abstration layer for its abstract equivalent (reserved resources in D3D12, etc.).
Do you have any plan to add this part to DiligentCore ?
Thanks a lot, a congratulation for your work (just discovered it a week ago) !

**Comment by DiligentGraphics** [comment]
Yes, partially resident resources are not currently exposed in the common API, but are planned (https://github.com/DiligentGraphics/DiligentCore/issues/52). The overall plan is to keep extending the API with more advanced features (multiple command queues, render passes, ray tracing, etc.). Since out bandwidth is limited, the exact order depends on what developers want in the first place. I will bump the priority of tiled resources since there have been interest in this feature.

**Comment by gjaegy** [comment]
Thanks, that's great!

⁣Télécharger BlueMail pour Android ​

Le 15 mars 2019 à 19:11, à 19:11, DiligentGraphics <notifications@github.com> a écrit:

**Comment by gjaegy** [comment]
Oui c'est bien ça. C'est bien on peut utiliser le même système pour les IB/VB également !

https://github.com/DiligentGraphics/DiligentCore/issues/77#issuecomment-473390593

Pas encore implémenté dans le wrapper en question. Mais le gars est hyper réactif !

⁣Télécharger BlueMail pour Android ​

Le 15 mars 2019 à 19:11, à 19:11, DiligentGraphics <notifications@github.com> a écrit:

**Comment by DiligentGraphics** [comment]
Closing this issue as there is https://github.com/DiligentGraphics/DiligentCore/issues/52. Please feel free to reopen if you have more questions.
