### ISSUE TITLE
Updating constant buffers.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#85]
Hello, I have been encountering a very strange bug with diligent recently that is currently slowing me down.

So, I have a pipeline that is correctly created and got 2 constant buffers one is in the vertex shader, and the other is in the pixel shader.
It seems that updating those constant buffers by mapping fills them with corrupted data in DirectX while in vulkan it is filled with zeros.

I am 100% sure that the pointer to data in memeory is correct.
I tried graphical debugging with Visual studio and I made sure that the buffers are correctly bound to the Pipeline/shader.
I know that the issue is not clear but this is what really happens.

Do you have any idea why this happens?
You can check the source code [here](https://github.com/Zone-organization/Nuclear-Engine
).

Creating the pipeline and setting the static buffers and updating the light buffer "in the Pixel shader' [here](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Systems/RenderSystem.cpp).

Updating the camera buffer [here](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Components/CameraComponent.cpp)

**Comment by DiligentGraphics** [comment]
[This code](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Systems/RenderSystem.cpp#L237)
```cpp
data = mPSLightCB;
```
does not make any sense. It overwrites mapped data pointer with the pointer to your constant buffer. As a result, no data is written to the buffer and the shader reads unitialized memory (which can be either garbage or zeros). Same situation with [CameraComponent](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Components/CameraComponent.cpp#L68).
What you were intending to write was [something like this](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial02_Cube/src/Tutorial02_Cube.cpp#L220) (I would suggest using `MapHelper` class as it takes care of unmapping the buffer when it goes out of scope).
Otherwise you need to write something like
```cpp
*reinterpret_cast<CameraBuffer*>(data) = _CameraBuffer;
```

**Comment by zlixine** [comment]
Thank you.
About the light constant buffer, I feel very dumb that I didn't notice that bug thanks for pointing it out.
And yes I intended to replace the map helper class as I tried to use it but it didn't work so thanks again.

**Comment by zlixine** [comment]
Also one last thing, The Light constant buffer is being dynamically built at runtime, so its size isn't known at compile time, so it can't use map helper class.
Any thoughts how to work around that?

**Comment by DiligentGraphics** [comment]
Oftentimes it requires somebody else to look at your code to spot an obvious problem :)
As to buffer update, you have few options.
If your maximum number of lights is limited to a reasonable number and if you update your buffer once per frame, you can just reserve enough space for maximum number of lights. That should work fine.
If you update your buffer multiple times per frame or if you need to write considerable amount of data, I would recommend the streaming method used in [Tutorial10](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial10_DataStreaming). Instead of writing lights to a constant buffer, make the buffer a shader resource and read it in the shader using offset. Fill the buffer with nooverwrite flag until it fills up and then discard it. Make current offset available to your shader via constant buffer.
