### ISSUE TITLE
Avoiding the need to have SPIRV and friends projects.

### ISSUE THREAD

**Issue by raxvan** [DiligentGraphics/DiligentCore#90]
As far as i can see DiligentCore depends on SPIRV-Cross repo and other similar. Is there a way to avoid the need to have this projects by optionally removing `GLSLSourceBuilder::BuildGLSLSourceString` function at compile time?

I would like to be able to "build" that glsl offline and just load that at runtime.

**Comment by DiligentGraphics** [comment]
If you don't want to build glslang, SPIRV-Tools and other modules required for run-time shader compilation, you can set `DILIGENT_NO_GLSLANG` cmake option. In this case Vulkan backend will only take compiled SPIRV bytecode.
There are other [build options](https://github.com/DiligentGraphics/DiligentEngine#build-options). 
SPIRV-Cross, however, is the only module that will always be built because it is used for shader reflection (there are only 4 source files though).

`BuildGLSLSourceString` is used to process shader source and add some platform/API specific definitions in GL/Vulkan backend and isn't really related to SPIRV-Cross. Right now there is no way to avoid this pre-processing, but it is easy to add.

**Comment by TheMostDiligent** [comment]
There are now `DILIGENT_NO_GLSLANG` and `DILIGENT_NO_HLSL` CMake options that allow completely removing run-time SPIRV compilation and HLSL2GLSL conversions. There is also `SHADER_SOURCE_LANGUAGE_GLSL_VERBATIM` language type that specifies that GLSL source should be taken verbatim without any changes.
